version: "3.8"

services:
  devcontainer-88:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspaces/Gestion_Menage
    environment:
      NODE_ENV: development
    networks:
      - devcontainer-networks

  db:
    image: postgres:13
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devcontainer-networks

volumes:
  pgdata:

networks:
  devcontainer-networks:
    driver: bridge
